title = "Han"
theme = "flat"
themesDir = "themes"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4
baseURL = "https://zzuhann.work/"
post = "/:slug/"

disqusShortname = "https-www-zzuhann-work"

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
description = "紀錄 han 的前端/生活/各種筆記與日常～！"
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

[[menus.main]]
pageref = "about"
name = "About"
weight = 80

[taxonomies]
  category = "categories"
  tag = "tags"
  

[sitemap]
changefreq = "monthly"
disable = false
filename = "sitemap.xml"
priority = 0.5

googleAnalytics = "G-ZRE1K2XSPN"

